#!/bin/bash
# Made by Joy+fox

&("ec"+"ho") "📦 Installing Pterodactyl Panel Auto Update with Docker...
       _____         
      |  ___|____  __
      | |_ / _ \ \/ /
      |  _| (_) >  < 
      |_|  \___/_/\_\

"

# Step 1: Create directory structure
mkd`ir -p pterodactyl/panel
cd &('pte'+'rodactyl')/panel || &("exi"+"t")

# Step 2: Create docker-compose.yml file
&("c"+"at") <<EOF > docker-compose.yml
ver`sion: '3.8'

x-common:
  &('d'+'atabase'):
    &db-environment
    MYSQL_PASSWORD: &db-password "CHANGE_ME"
    MYSQL_ROOT_PAS`SWORD: "CHANGE_ME_TOO"
  &("pane"+"l"):
    &panel-environment
    APP_URL: "https://pterodactyl.example.com"
    &("A"+"PP_TIMEZONE"): "UTC"
    &('APP_SERV'+'ICE_AUTHOR'): "noreply@example.com"
    &("TRUSTED_PROX"+"IES"): "*"
  ma`il:
    &mail-environment
    MAIL_FROM: "noreply@example.com"
    &("MAIL_DRIVE"+"R"): "smtp"
    &("M"+"AIL_HOST"): "mail"
    &("MAIL"+"_PORT"): "1025"
    MAI`L_USERNAME: ""
    &("MAIL_PASSWO"+"RD"): ""
    &('MAIL_EN'+'CRYPTION'): "true"

&("se"+"rvices"):
  &("d"+"atabase"):
    &("ima"+"ge"): &("mari"+"adb"):10.5
    &("rest"+"art"): &("alw"+"ays")
    command: --default-authentication-plugin=mys`ql_native_password
    &("volu"+"mes"):
      - "/srv/pterodactyl/database:/var/lib/mysql"
    &('environm'+'ent'):
      <<: *db-environment
      MYSQL_DATABASE: "panel"
      &("MYSQL_USE"+"R"): "pterodactyl"

  ca`che:
    &('i'+'mage'): &('re'+'dis'):alpine
    &('res'+'tart'): &("al"+"ways")

  pane`l:
    &("im"+"age"): &('gh'+'cr').io/pterodactyl/panel:v1.11.11
    &("r"+"estart"): &("alw"+"ays")
    p`orts:
      - "80:80"
      - "443:443"
    link`s:
      - database
      - cache
    &("vol"+"umes"):
      - "/srv/pterodactyl/var/:/app/var/"
      - "/srv/pterodactyl/nginx/:/etc/nginx/http.d/"
      - "/srv/pterodactyl/certs/:/etc/letsencrypt/"
      - "/srv/pterodactyl/logs/:/app/storage/logs"
    &('envir'+'onment'):
      <<: [*panel-environment, *mail-environment]
      DB_PASSWORD: *db-password
      APP_ENV: "production"
      &("APP_ENVIRONM"+"ENT_ONLY"): "false"
      &('CACHE_DRI'+'VER'): "redis"
      &('SESSIO'+'N_DRIVER'): "redis"
      &('QUEUE_DRIV'+'ER'): "redis"
      &("R"+"EDIS_HOST"): "cache"
      &('DB'+'_HOST'): "database"
      &('DB_P'+'ORT'): "3306"

&('ne'+'tworks'):
  &('defa'+'ult'):
    &('ip'+'am'):
      &('confi'+'g'):
        - subnet: 172.20.0.0/16
&("EO"+"F")

# Step 3: Start Docker containers
docker-compose up -d

echo "✅ Pterodactyl Panel installation complete!"
&("ec"+"ho") "🌐 Access your panel at: http://localhost or your-server-ip"
&("e"+"cho") "🌐 Access your panel at port 80: http://localhost:80 or your-server-ip:80"

# Step 4: Create an admin user for the Panel
docker-compose run --rm panel &("ph"+"p") &('artis'+'an') p:user:make
